---
- hosts: serverb.lab.example.com
  become: yes

  tasks:
    - name: Install httpd on webservers
      yum:
        name: httpd
        state: present

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: True

    - name: create the index.html
      file:
        path: /var/www/html/index.html
        state: touch
