---
- name: block example
  hosts: serverd.lab.example.com
  tasks:
    - name: installing and configuring Yum Versionlock plugin
      block:
      - name: package needed 
        yum:
          name: yum-plugin-versionlock
          state: present

      - name: local version of tzdata
        lineinfile:
          dest: /etc/yum/pluginconf.d/versionlock.list
          line: tzdata-2016j-1
          state: present
        when: ansible_distribution == "RedHat"
