### Steps to configure the webserver using httpd       
# 1. Install the package httpd using dnf or yum             -> ansible module ( dnf or yum )
# 2. Copy the index.html to DocumentRoot /var/www/html      -> ansible module ( copy )
# 3. Start and enable the httpd service                     -> ansible module ( service )
# 4. Allow http serivce from Firewalld                     -> ansible module ( firewalld )
# 5. Test the connectivity to webserver                     -> ansible module ( uri )

---
- name: Setup the webserver 
  hosts: development
  tasks:

    - name: Install the httpd package 
      yum:
        name: httpd
        state: latest
       
    - name: Correct index.html is present 
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: True

    - name: Create firewall rules
      firewalld:
        service: http
        state: enabled
        immediate: True
        permanent: True

- name: Test Connectivity to Webserbers
  hosts: localhost
  become: false 
  tasks:
    - name: Connect to webserver
      uri:
        url: http://servera.lab.example.com
        return_content: yes
        status_code: 200
      register: output

    - name: show the content of the captured output
      debug:
        var: output
