---
- name: Template to setup a ssh
  hosts: serverc.lab.example.com
  
  tasks:
    - name: include the variables
      include_vars: vhost.vars


    - name: Install the openssh
      yum:
        name: openssh-server
        state: installed

    - name: Render the configuration from j2 template
      template:
        src: vhost.template.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root


    - name: start and enable service
      service:
        name: sshd
        state: restarted
        enabled: yes

    - name: Open the port in the firewall
      firewalld:
        service: ssh
        state: enabled
        immediate: true
        permanent: true
