## Create a user fred with Fullname Fred, Lastname Flinstone, Home /home/fflintstone, and Shell as /bin/sh

---
- name: Create user with Array example
  hosts: servera.lab.example.com
  vars:
    users:
      fflintstone:
        uname: fred
        fname: Fred
        lname: Flintstone
        home: /home/fflintstone
        shell: /bin/sh

  tasks:
    - name: Create a user
      user:
        name: "{{ users['fflintstone']['uname'] }}"
        comment: "{{ users['fflintstone']['fname'] }} {{ users['fflintstone']['lname'] }}"
        shell: "{{ users['fflintstone']['shell'] }}"
        state: present
