---
- name: install and configu webserver 
  hosts: 
    - servera.lab.example.com
    - serverb.lab.example.com
    - serverc.lab.example.com
    - serverd.lab.example.com

  tasks:

    - name: Import the web_tasks.yml taks file
      import_tasks: tasks/web_tasks.yml

    - name: Enable and start the firewall
      service:
        name: firewalld
        enabled: true
        state: started 

    - name: Open the port for http
      firewalld:
        service: http
        immediate: true
        state: enabled 
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
