### Task to update the resolv.conf DNS entry
---
- name: Idempotent
  hosts: servera.lab.example.com
  tasks: 
    - name: update resolv.conf
      copy:
        content: nameserver 8.8.8.8
        dest: /etc/resolv.conf
...

