---
- hosts: serverc.lab.example.com
  become: yes
  tasks:

    - name: Install the httpd package
      yum:
        name: httpd
        state: latest

    - name: update httpd.conf
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin.*$'
        replace: 'ServerAdmin admin@serverc.lab.example.com'
        backup: yes
      notify: "restart web server"

  handlers:
    - name: "restart apache"
      service:
        name: httpd
        state: restarted
      listen: "restart web server"

