---
- name: test when condition
  hosts: servera.lab.example.com
  tasks:
    - name: check postfix is active
      command: /usr/bin/systemctl is-active postfix
      ignore_errors: True
      register: result

    - name: restart apache httpd on postfix status
      service: 
        name: httpd
        state: restarted
      when: result.rc == 0
      
    - name: check the outout 
      debug:
        var: result
