### Steps to configure the webserver using httpd       
# 1. Install the package httpd using dnf or yum             -> ansible module ( dnf or yum )
# 2. Copy the index.html to DocumentRoot /var/www/html      -> ansible module ( copy )
# 3. Start and enable the httpd service                     -> ansible module ( service )

---
- name: Setup the webserver 
  hosts: servera.lab.example.com
  tasks:

    - name: Install the httpd package 
      yum:
        name: httpd
        state: latest
       
    - name: Correct index.html is present 
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: True
