---
- name: Display some basic facts
  hosts: servera.lab.example.com
  gather_facts: false
  tasks:
    - name: show some properties of {{ inventory_hostname }}
      debug:
        msg: >
          my FQDN is {{ ansible_facts['fqdn'] }} and my default IPaddress is {{ ansible_facts['default_ipv4']['address'] }}
...
