### Create the user with password  ---> ansible module user
#
---
- name: Create users
  hosts: servera.lab.example.com
  vars:
    username: fred
    password: bedrock
  tasks:
    - name: create users
      user: 
        name: "{{ username }}"
        password: "{{ password  | password_hash ('sha512') }}"
        state: present
     
