---
- name: configure SOE
  hosts: all
  vars:
    - system_owner: admin@example.com

  tasks:
    - name: configure /etc/motd
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
