---
- name: DB server playbook
  become: True
  hosts: serverb.lab.example.com
  tasks:
    
    - name: Add the 'dba' user to the dbserver
      user:
        name: dba
        state: present

    - name: Copy requried DBA files
      copy:
        src: files/DBAstuff.txt
        dest: /home/dba
        owner: dba
        group: dba
        mode: 0600
