---
- name: Rolling update
  hosts: webservers
  serial: 2
  tasks:

  - name: latest apache httpd package is installed 
    yum:
      name: httpd
      state: latest
    notify: restart apache

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted

