---
dependencies: []

galaxy_info:
  role_name: ssh-chroot-jail
  author: geerlingguy
  description: Simple SSH chroot jail management.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
    - security
    - chroot
    - ssh
    - jail
    - lockdown
    - access
