---
- name: create the user 
  hosts: servera.lab.example.com
  tasks:
        
   - name: Create the user test2 and member of wheel group
     user:
       name: test2
       comment: Test2 User
       group: wheel
       state: present
