### Task to update the resolv.conf DNS entry
---
- name: Not Idempotent
  hosts: servera.lab.example.com
  tasks: 
    - name: update resolv.conf
      shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

...

