---
- name: playbook for role syntax
  hosts: servera.lab.example.com


  pre_tasks:
    - name:
      debug:
        msg: "pre_tasks output"
      notify: myhandler


  roles:
    - roles/sunny.usertest

  tasks:
    - name:
      debug:
        msg: 'first task1'
      notify: myhandler

  post_tasks:
    - name: 
      debug: 
        msg: 'post-task output'
      notify: myhandler

  handlers:
  - name: myhandler
    debug:
      msg: "handler excuted"
