---
- name: Conditional playbook
  hosts: all
  become: True
  
  tasks:
    - name: Install the tar package
      yum:
        name: backup_prodevans
        state: latest
      ignore_errors: true

    - name: Check for archive file
      command: ls /root/archives.tar
      register: check_result
      ignore_errors: true

    - name: Create archive file
      file:
        path: /root/archives.tar
        state: touch
      when: check_result is failed

        
