### Copy three lines in the destiation file    -->    ansible module ( copy )
#   Copy one long single line in the dest file -->    ansible module ( copy )
#
--- 
- name: Copy No of lines using copy module 
  hosts: servera.lab.example.com
  tasks: 

  - name: Copy three lines to /var/tmp/lots_of_lines
    copy:
      content: |
        This is line 1
        Tthis is line 2
        Finally, This is another line in line3
      dest: /var/tmp/lots_of_lines

  - name: Copy the one long line  to /var/tmp/one_line
    copy: 
      content: >
        This is one really long time that 
        looks like it may be finalized
        as many lines but beacuse of the > character,
        it will be collopased as 1 line 
      dest: /var/tmp/one_line
